In [1]:
import numpy as np

In [6]:
arr1 = np.array([1,2,3,4,5,6,7,8])
print(arr1)

[1 2 3 4 5 6 7 8]


In [2]:
arr2 = np.array([[1,2,3,],[4,5,6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [3]:
arr3 = np.array([[[1,2,3,],[4,5,6]] , [[11,22,30,],[41,5,56]]])
print(arr3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[11 22 30]
  [41  5 56]]]


In [4]:
arr4 = np.array([[[1,2,3,],[4,5,6],[7,8,9]]])
print(arr4)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [7]:
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)
print(arr4.ndim)

1
2
3
3


In [8]:
arr5 = np.array([1,2,3,4,5], ndmin=5)
print(arr5)
print('Number of dimentions:', arr5.ndim)

[[[[[1 2 3 4 5]]]]]
Number pf dimentions: 5


In [10]:
arr6 = np.array([], ndmin=6)
print(arr6)
print('Number of dimentions:', arr6.ndim)

[]
Number of dimentions: 6


In [11]:
arr6 = np.array([1], ndmin=6)
print(arr6)
print('Number of dimentions:', arr6.ndim)

[[[[[[1]]]]]]
Number of dimentions: 6


In [13]:
arr6 = np.array([[1],[2],[3]], ndmin=6)
print(arr6)
print('Number of dimentions:', arr6.ndim)

[[[[[[1]
     [2]
     [3]]]]]]
Number of dimentions: 6


In [17]:
arr7 = np.array([1,2,3,4,5])
print(arr7[0])
print(arr7[0:2])
print(arr7[0::2])
print(arr7[0::-1])
print(arr7[::-1])

1
[1 2]
[1 3 5]
[1]
[5 4 3 2 1]


In [23]:
arr8 = np.array([[1,2,3,],[4,5,6]])
print(arr8[0,0])
print(arr8[0,1])
print(arr8[0,2])
print(arr8[1,0])
print(arr8[1,1])
print(arr8[1,2])             #accessing values in multi dimention
print(arr8[-1,-1])           #negative indexing
print(arr8[-1,-2])

1
2
3
4
5
6
6
5


In [26]:
arr9 = np.array([[[1,2,3,],[4,5,6]] , [[11,21,30,],[41,52,56]]])
print(arr9[0,1,2])
print(arr9[1,1,2])
print(arr9[1,0,2])
print(arr9[1,0,1])

6
56
30
21


In [33]:
#Slicing
arr7 = np.array([1,2,3,4,5])
l = arr7[1:4]
print(l)
l2 = list(l)    #constructor
print("type of l2: ",type(l2))
print(type(l))
l3 = list(arr7)
print(type(l3))
print(l3)

[2 3 4]
type of l2:  <class 'list'>
<class 'numpy.ndarray'>
<class 'list'>
[1, 2, 3, 4, 5]


In [36]:
arr7 = np.array([1,2,3,4,5])
print(arr7[-3:-1])
print([arr7[-3:-1]])

[3 4]
[array([3, 4])]


In [42]:
arr9 = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
print(arr9)
print(arr9[1:4,1:3])

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
[[8 9]]


In [43]:
arr2 = np.array([1,2,3,4,1.1])
print(arr2.dtype)

float64


In [45]:
arr2 = np.array([1,2,3,4,"NTT"])
print(arr2.dtype)

<U21


In [47]:
arr2 = np.array([1,2,3,4,1.1])
print(arr2.dtype)
print(arr2[0]+arr2[1])

float64
3.0


In [48]:
arr2 = np.array([1,2,3,4,"NTT"])
print(arr2.dtype)
print(arr2[0]+arr2[4]) #concatination has happened.

<U21
1NTT


In [50]:
arr = np.array([1,2,3,4], dtype="S")  #specifying the datatype as String
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [51]:
arr = np.array([1,2,3,4], dtype="i4")  #specifying the datatype as String
print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [52]:
arr = np.array([1,2,3,4], dtype="i8")  #specifying the datatype as String
print(arr)
print(arr.dtype)

[1 2 3 4]
int64


In [53]:
arr2 = np.array([1.1,2.0,3.0,4.0,5])
na = arr2.astype("i")
print(na)
print(na.dtype)

[1 2 3 4 5]
int32


In [54]:
arr2 = np.array([1.1,2.0,3.0,4.0,5])
na = arr2.astype(int)
print(na)
print(na.dtype)

[1 2 3 4 5]
int64


In [59]:
arr2 = np.array([1.1,2.0,3.0,4.0,0.0])
na = arr2.astype(bool)
print(na)
print(na.dtype)

[ True  True  True  True False]
bool


In [60]:
# copy vs view
arr = np.array([1,2,3,4,5])
x=arr.copy()
arr[0] = 42
print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [61]:
arr = np.array([1,2,3,4,5])
x=arr.view()
arr[0] = 42
print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [63]:
#Numpy Array Shape

arr3 = np.array([[1,2,3,8,9,10],[4,5,6,9,9,9]])
print(arr3.shape)

(2, 6)


In [64]:
arr = np.array([1,2,3,4],ndmin=5)
print(arr)
print('Shape pf array :', arr.shape)

[[[[[1 2 3 4]]]]]
Shape pf array : (1, 1, 1, 1, 4)


In [65]:
arr = np.array([[1,2,3,4],[8,9,10,11]],ndmin=5)
print(arr)
print('Shape pf array :', arr.shape)

[[[[[ 1  2  3  4]
    [ 8  9 10 11]]]]]
Shape pf array : (1, 1, 1, 2, 4)


In [66]:
arr = np.array([[[1,2,3,4],[8,9,10,11]],[[1,2,3,4],[8,9,10,11]]],ndmin=5)
print(arr)
print('Shape pf array :', arr.shape)

[[[[[ 1  2  3  4]
    [ 8  9 10 11]]

   [[ 1  2  3  4]
    [ 8  9 10 11]]]]]
Shape pf array : (1, 1, 2, 2, 4)


In [67]:
#Reshaping

arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr= arr.reshape(4,3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [68]:
#Reshaping

arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr= arr.reshape(2,3,2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [69]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13])
newarr= arr.reshape(2,3,2)
print(newarr)

ValueError: cannot reshape array of size 13 into shape (2,3,2)

In [77]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,0,12])
newarr= arr.reshape(2,3,2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [ 0 12]]]


In [80]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,0,12])
newarr= arr.reshape(2,2,3)
print(newarr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10  0 12]]]


In [78]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,0,12])
newarr= arr.reshape(2,2,-1)
print(newarr)
print(newarr.shape)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10  0 12]]]
(2, 2, 3)


In [81]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,0,12])
newarr= arr.reshape(2,-1,2)
print(newarr)
print(newarr.shape)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [ 0 12]]]
(2, 3, 2)


In [83]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,0,12])
newarr= arr.reshape(2,-1,-1)
print(newarr)
print(newarr.shape)

ValueError: can only specify one unknown dimension

In [85]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,0,12])
newarr= arr.reshape(2,-1,3)
print(newarr)
print(newarr.shape)
na = newarr

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10  0 12]]]
(2, 2, 3)


In [86]:
print(na)
nna = na.reshape(-1)
print(nna)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10  0 12]]]
[ 1  2  3  4  5  6  7  8  9 10  0 12]
