In [ ]:
# List Introduction

l = [10, 20, 30]
print("Print the list l as", l)

Print the list l as [10, 20, 30]


In [ ]:
# Checking the type of data structure
print(type(l))

<class 'list'>


In [ ]:
# List as heterogenous
l2 = [10, 20, 1.1111, "NTT"]
print(l2)

[10, 20, 1.1111, 'NTT']


In [ ]:
# Finding length of the list
print(len(l2))

3


In [ ]:
# list creation using Constructor List()

l3 = list((10, 20, 3.3333))
print(l3)
print(type(l3))

[10, 20, 3.3333]
<class 'list'>


In [ ]:
# Accessing elements in th list .. by using index.. indexing

lis = [10,20,30,40,50,60,1.1,2.2,"NTT"]

#Positive indexing
print(lis[0])
print(lis[1])
print(lis[2])
print(lis[3])
print(lis[4])
print(lis[5])
print(lis[6])
print(lis[8])

10
20
30
40
50
60
1.1
NTT


In [ ]:
#Negative indexing
print(lis[-1])
print(lis[-2])
print(lis[-3])
print(lis[-4])
print(lis[-5])
print(lis[-6])
print(lis[-8])

NTT
2.2
1.1
60
50
40
20


In [ ]:
# range of positive index.. ending parameter will be excluded

l = [10, 20, 30, 40, 50 ,60, 70, 80]
print(l[2])
print(l[0:7])
print(l[2:6])
print(l[3:4])


30
[10, 20, 30, 40, 50, 60, 70]
[30, 40, 50, 60]
[40]


In [ ]:
# range of negative index.. ending parameter will be excluded

l = [10, 20, 30, 40, 50 ,60, 70, 80]
print(l[-5:-1]) # start index should be smaller since -5 is smaller than -1
print(l[0:8]) # to get the index
print(l[2:10])


[40, 50, 60, 70]
[10, 20, 30, 40, 50, 60, 70, 80]
[30, 40, 50, 60, 70, 80]


In [ ]:
print(l[8])  # point to index which do not exist will show error

IndexError: list index out of range

In [ ]:
# range 3 parameter

l = [10, 20, 30, 40, 50 ,60, 70, 80]
print(l[0:8:1])  # 3rd param minus 1 to skip the index
print(l[0:8:2])
print(l[0:8:3])

[10, 20, 30, 40, 50, 60, 70, 80]
[10, 30, 50, 70]
[10, 40, 70]


In [ ]:
# optional range parameter

l = [10, 20, 30, 40, 50 ,60, 70, 80]
print(l[0:]) # by default the end index will be the last index
print(l[:5]) # by default the start index is 0
print(l[::]) # print full list, by default the step index will be -1.. so -1 minus with 1 will be 0
print(l[::-1]) # to reverse

[10, 20, 30, 40, 50, 60, 70, 80]
[10, 20, 30, 40, 50]
[10, 20, 30, 40, 50, 60, 70, 80]
[80, 70, 60, 50, 40, 30, 20, 10]


In [ ]:
l = [10, 20, 30, 40]
l[0] = 200
print("The index 0 will be replaced",l)
l[1:3] = ['NTT', 400]
print(l)

The index 0 will be replaced [200, 20, 30, 40]
[200, 'NTT', 400, 40]


In [ ]:
l = [10, 20, 30, 40, 50 ,60, 70, 80]
print(l[-5:-1:-1])

[]


In [ ]:
l = [10, 20, 30, 40, 50 ,60, 70, 80]
print(l[-5:-1:1])

[40, 50, 60, 70]


In [ ]:
l = [10, 20, 30, 40, 50 ,60, 70, 80]
print(l[5:1:-1])

[60, 50, 40, 30]


In [ ]:
l = [10, 20, 30, 40, 50 ,60, 70, 80]
print(l[1:5:1])

[20, 30, 40, 50]


In [ ]:
l = [10, 20, 30, 40, 50 ,60, 70, 80]
print(l[5:1:1])

[]


In [ ]:
l = [10, 20, 30, 40, 50 ,60, 70, 80]
print(l[5:1])

[]


In [ ]:
l = [10, 20, 30, 40, 50 ,60, 70, 80]
print(l[-1:-8:-1])

[80, 70, 60, 50, 40, 30, 20]


In [ ]:
l = [10, 20, 30, 40, 50 ,60, 70, 80]
print(l[-8:-1:-1])

[]


In [ ]:
l = [10, 20, 30, 40, 50 ,60, 70, 80]
print(l[-8:-1:1])

[10, 20, 30, 40, 50, 60, 70]


In [ ]:
l = [10, 20, 30, 40, 50 ,60, 70, 80]
print(l[-10:-1:1])

[10, 20, 30, 40, 50, 60, 70]


In [ ]:
l = [10, 20, 30, 40]
l[1:2] = [88,99]
print(l)

[10, 88, 99, 30, 40]


In [ ]:
l = [10, 20, 30, 40]
l[1:7] = [88]
print(l)

[10, 88]


In [ ]:
l = [10, 20, 30, 40]
l[3] = [88,99,100]
print(l)

[10, 20, 30, [88, 99, 100]]


In [ ]:
l = [10, 20, 30, 40]
l[3:4] = [88,99,100]
print(l)

[10, 20, 30, 88, 99, 100]


In [ ]:
#append .. add only one element to the end of the list
l = [10, 20, 30, 40, 50 ,60, 70, 80]
l.append(90)
print(l)

[10, 20, 30, 40, 50, 60, 70, 80, 90]


In [ ]:
#insert .. inserting values in the location
l = [10, 20, 30, 40, 50 ,60, 70, 80, 90]
l.insert(1,15)
print(l)

[10, 15, 20, 30, 40, 50, 60, 70, 80, 90]


In [ ]:
# extend

l1 = [10,20,30]
l2 = [40,50,60]
l3 = [80, 90]

l1.extend(l2)
print(l1)
print(l2)
print(l3)

l1.extend(l3)
print(l1)


[10, 20, 30, 40, 50, 60]
[40, 50, 60]
[80, 90]
[10, 20, 30, 40, 50, 60, 80, 90]


In [ ]:
# remove the matching value from the list

l1 = [10,20,30]
l1.remove(20)
print(l1)

[10, 30]


In [ ]:
# pop function

l1 = [10,20,30, 40]
l1.pop()
print(l1)

[10, 20, 30]


In [ ]:
# pop function... index value will be deleted

l1 = [10,20,30, 40]
l1.pop(2)
print(l1)

[10, 20, 40]


In [ ]:
# del function

l1 = [10,20,30, 40]
print(l1)

del l1

print(l1)

[10, 20, 30, 40]


NameError: name 'l1' is not defined

In [ ]:
# del function

l1 = [10,20,30, 40]
print(l1)

del l1[0:2]

print(l1)

[10, 20, 30, 40]
[30, 40]


In [ ]:
# clear function to clearing the values in the list without deleting list
l1 = [10,20,30, 40]
l1.clear()
print(l1)

[]


In [ ]:
# for loop

l1 = [10, 20, 30, 40, 50, 60, 70, 80]

for i in l1:
  print(i)

10
20
30
40
50
60
70
80


In [ ]:
# for loop

l1 = [10, 20, 30, 40, 50, 60, 70, 80]

for i in l1[0:4]:
  print(i)

10
20
30
40


In [ ]:
# for loop

l1 = [10, 20, 30, 40, 50, 60, 70, 80]

for i in l1[3:4]:
  print(i)

40


In [ ]:
# for loop

l1 = [10, 20, 30, 40, 50, 60, 70, 80]

for i in l1:
  print(i)
  print(i+5)

print(l)

10
15
20
25
30
35
40
45
50
55
60
65
70
75
80
85
[10, 15, 20, 30, 40, 50, 60, 70, 80, 90]


In [1]:
print("day 3")

day 3


In [3]:
t1 = (1,2,3,40,"NTT", 1.1)
print(t1)

(1, 2, 3, 40, 'NTT', 1.1)


In [5]:
print(type(t1))

<class 'tuple'>


In [6]:
#constructor tuple to create a tuple
t2 = tuple((3,40,"NTT", 1.1))
print(t2)

(3, 40, 'NTT', 1.1)


In [9]:
t3 = tuple([3,40,"NTT", 1.1]) #list is converted to tuple
print(t3)
print(type(t3))

(3, 40, 'NTT', 1.1)
<class 'tuple'>


In [11]:
t4 = tuple((15))
print(t4)
print(type(t4))

TypeError: 'int' object is not iterable

In [12]:
t4 = tuple((15,))
print(t4)
print(type(t4))

(15,)
<class 'tuple'>


In [13]:
t4 = tuple(("NTT"))
print(t4)
print(type(t4))

('N', 'T', 'T')
<class 'tuple'>


In [14]:
t4 = tuple(('NTT')) #iterable element
print(t4)
print(type(t4))

('N', 'T', 'T')
<class 'tuple'>


In [15]:
t4 = tuple(('NTT', 'DATA'))
print(t4)
print(type(t4))

('NTT', 'DATA')
<class 'tuple'>


In [16]:
t4 = tuple(('NTT',))
print(t4)
print(type(t4))

('NTT',)
<class 'tuple'>


In [17]:
for i in "NTT":
  print(i)

N
T
T


In [19]:
t6 = tuple((15, 16))
print(t6)

(15, 16)


In [20]:
a = (15)
print(a)
print(type(a))


15
<class 'int'>


In [21]:
a = (15,)
print(a)
print(type(a))

(15,)
<class 'tuple'>


In [22]:
a = (15,15)
print(a)
print(type(a))

(15, 15)
<class 'tuple'>


In [25]:
#Accessing Tuple
t7 = (22,33,44,55,66,77)
print(t7[1])
print(t7[-1])
print(t7[2:10])

33
77
(44, 55, 66, 77)


In [26]:
print(t7[10])

IndexError: tuple index out of range

In [27]:
print(t7[-4:-1])

(44, 55, 66)


In [28]:
#Accessing Tuple
t7 = (22,33,44,55,66,77)
print(t7[1])
print(t7[-1])
print(t7[2:10])
print(t7[-4:-1:1])

33
77
(44, 55, 66, 77)
(44, 55, 66)


In [29]:
if 77 in t7:
  print("Yes")
else:
  print("No")

Yes


In [30]:
if "77" in t7:
  print("Yes")
else:
  print("No")

No


In [31]:
#Update
t7[0] = 100

TypeError: 'tuple' object does not support item assignment

In [32]:
# Append and insert method is not possible in Tuple

In [35]:
t7 = (22,33,44,55,66,77)
t8 = list(t7)
print(t8)
print(type(t8))
t8[0] = 100
t7 = tuple(t8)
print(t7)

[22, 33, 44, 55, 66, 77]
<class 'list'>
(100, 33, 44, 55, 66, 77)


In [36]:
del t7[0]

TypeError: 'tuple' object doesn't support item deletion

In [39]:
del t6

In [40]:
#Iterate

t7 = (22,33,44,55,66,77)

for i in t7:
  print(i)

22
33
44
55
66
77


In [42]:
s = [["akash", 25, "BE"], ["John", 22, "BSC"], ["Smith", 21, "MBBS"]] #Nested list
print(s)
print(type(s))
print(s[1])

[['akash', 25, 'BE'], ['John', 22, 'BSC'], ['Smith', 21, 'MBBS']]
<class 'list'>
['John', 22, 'BSC']


In [45]:
from os import name
#Dictionary

d = {'name':"akash",'age': 25, 'course':"BE"}
print(d)
print(type(d))
print(d['name'])

{'name': 'akash', 'age': 25, 'course': 'BE'}
<class 'dict'>
akash


In [46]:
d2 = {10:11111, 20:22222}
print(d2[10])

11111


In [48]:
d3 = {"usn1":["akash", 25, "BE"], "usn2": ["John", 22, "BSC"],"usn3": ["Smith", 21, "MBBS"]}
print(d3["usn1"])
print(len(d3))

['akash', 25, 'BE']
3


In [50]:
x = d3.keys() # fetch keys of the dictionary
print(x)

dict_keys(['usn1', 'usn2', 'usn3'])


In [52]:
y = d3.values() #fetch values in the dictionary
print(y)

dict_values([['akash', 25, 'BE'], ['John', 22, 'BSC'], ['Smith', 21, 'MBBS']])


In [53]:
z = d3.items()
print(z)

dict_items([('usn1', ['akash', 25, 'BE']), ('usn2', ['John', 22, 'BSC']), ('usn3', ['Smith', 21, 'MBBS'])])


In [54]:
#How to modify

d4 = {'name':"akash",'age': 25, 'course':"BE"}
d4["name"] = "John"
print(d4)

{'name': 'John', 'age': 25, 'course': 'BE'}


In [55]:
d4.update({"name":"Clara"})
print(d4)

{'name': 'Clara', 'age': 25, 'course': 'BE'}


In [56]:
d4["Country"] = "Norway"
print(d4)

{'name': 'Clara', 'age': 25, 'course': 'BE', 'Country': 'Norway'}


In [57]:
d4.popitem()
print(d4)

{'name': 'Clara', 'age': 25, 'course': 'BE'}


In [59]:
d4.pop("age")
print(d4)

{'name': 'Clara', 'course': 'BE'}


In [60]:
del d4['course']
print(d4)

{'name': 'Clara'}


In [61]:
del d4

In [63]:
d5 = {'name':"akash",'age': 25, 'course':"BE"} # Iterate

for i in d5:
  print(d5[i])

akash
25
BE


In [68]:
#Numpy package --> optional package
import numpy as np

arr = np.array([1,2,3,4,5])    #method array which is described in Numpy
print(arr)
print(type(arr))
print(arr.ndim)
print(arr.size)
print(arr.shape)   #shape of the array will be tuple
print(arr.dtype)

[1 2 3 4 5]
<class 'numpy.ndarray'>
1
5
(5,)
int64


In [72]:
arr2 = np.array([1,2,3,4,5,4.5])    #method array which is described in Numpy
print(arr2)
print(arr2.dtype)

[1.  2.  3.  4.  5.  4.5]
float64


In [74]:
arr3 = np.array([1,2,3,4,5,"NTT"])    #method array which is described in Numpy
print(arr3)
print(arr3.dtype)

['1' '2' '3' '4' '5' 'NTT']
<U21


In [80]:
arr2 = np.array([[1,2,3,],[4,5,6]])
print(arr2)
print(type(arr2))
print(arr2.ndim)
print(arr2.size)
print(arr2.shape)
print(arr2.dtype)

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
2
6
(2, 3)
int64


In [81]:
arr2 = np.array([[[1,2,3,],[4,5,6]] , [[11,22,30,],[41,5,56]]])
print(arr2)
print(type(arr2))
print(arr2.ndim)
print(arr2.size)
print(arr2.shape)
print(arr2.dtype)

[[[ 1  2  3]
  [ 4  5  6]]

 [[11 22 30]
  [41  5 56]]]
<class 'numpy.ndarray'>
3
12
(2, 2, 3)
int64
